import { CREATE_FILE_SET,CREATE_FILE_SET_ERROR,GET_FILE_SETS,GET_FILE_SETS_ERROR,UPDATE_FILE_SET,UPDATE_FILE_SET_ERROR,DELETE_FILE_SET,DELETE_FILE_SET_ERROR, GET_FILE_SETS_PAGINATED,GET_FILE_SETS_PAGINATED_ERROR,GET_FILE_SET,GET_FILE_SET_ERROR,GET_FILE_SET_DEFINITIONS,GET_FILE_SET_DEFINITIONS_ERROR,ADD_FILE_DEFINITIONS_TO_FILESET,ADD_FILE_DEFINITIONS_TO_FILESET_ERROR,DELETE_FILE_SET_FILE_DEFINITION,DELETE_FILE_SET_FILE_DEFINITION_ERROR,GET_FILE_SET_BATCHES_PAGINATED,GET_FILE_SET_BATCHES_PAGINATED_ERROR,GET_FILE_SET_DEFINITION_BATCHES_PAGINATED,GET_FILE_SET_DEFINITION_BATCHES_PAGINATED_ERROR,GET_FILE_SET_DEFINITION_BATCHES_TRANSACTIONS_PAGINATED,GET_FILE_SET_DEFINITION_BATCHES_TRANSACTIONS_PAGINATED_ERROR,GET_FILESET_BATCH_DETAIL,GET_FILESET_BATCH_DETAIL_ERROR,GET_FILESET_BATCH_DEFINITION_DETAIL,GET_FILESET_BATCH_DEFINITION_DETAIL_ERROR,GET_FILESET_BATCHES_SUMMARY,GET_FILESET_BATCHES_SUMMARY_ERROR,GET_FILE_SET_STATUS,GET_FILE_SET_STATUS_ERROR,GET_T112S,GET_T112S_ERROR,GET_T464S,GET_T464S_ERROR,GET_ADVISEMENT,GET_ADVISEMENT_ERROR,GET_T140S,GET_T140S_ERROR,GET_T464_TRANSACTIONS,GET_T464_TRANSACTIONS_ERROR,GET_T112_TRANSACTIONS,GET_T112_TRANSACTIONS_ERROR,GET_T112_SUMMARY,GET_T112_SUMMARY_ERROR,GET_T112_SUMMARY_LOADING,GET_T464_SUMMARY,GET_T464_SUMMARY_ERROR,GET_T461S,GET_T461S_ERROR,GET_T461_TRANSACTIONS,GET_T461_TRANSACTIONS_ERROR,GET_T140S_TRANSACTIONS,GET_T140S_TRANSACTIONS_ERROR,GET_T140S_TRANSACTIONS_LOADING,GET_INTERAFILIATE_ISSUERS,GET_INTERAFILIATE_ISSUERS_ERROR,GET_INTERAFILIATE_ACQUIRER,GET_INTERAFILIATE_ACQUIRER_ERROR,GET_ACQUIRER_TRANSACTIONS,GET_ACQUIRER_TRANSACTIONS_ERROR,GET_ISSUER_TRANSACTIONS,GET_ISSUER_TRANSACTIONS_ERROR,GET_VISA_ISSUER,GET_VISA_ISSUER_ERROR,GET_VISA_ISSUER_TRANSACTIONS,GET_VISA_ISSUER_TRANSACTIONS_ERROR, GET_VISA_ACQUIRER_ERROR,GET_VISA_ACQUIRER,GET_VISA_ACQUIRER_TRANSACTIONS,GET_VISA_ACQUIRER_TRANSACTIONS_ERROR,GET_INTERAFFILIATE_ACQUIRER_SUMMARY,GET_INTERAFFILIATE_ACQUIRER_SUMMARY_ERROR,GET_INTERAFFILIATE_ISSUER_SUMMARY,GET_INTERAFFILIATE_ISSUER_SUMMARY_ERROR,GET_INTERAFFILIATE_SUMMARY,GET_INTERAFFILIATE_SUMMARY_ERROR,GET_INTERAFFILIATE_SUMMARY_TRANSACTIONS,GET_INTERAFFILIATE_SUMMARY_TRANSACTIONS_ERROR,GET_VISA_ACQUIRER_SUMMARY,GET_VISA_ACQUIRER_SUMMARY_ERROR,GET_VISA_ISSUER_SUMMARY,GET_VISA_ISSUER_SUMMARY_ERROR,GET_VISA_ISSUER_SUMMARY_STATS,GET_VISA_ISSUER_SUMMARY_STATS_ERROR,GET_T112_SUMMARY_STATS,GET_T112_SUMMARY_STATS_ERROR,GET_T464_SUMMARY_STATS,GET_t464_SUMMARY_STATS_ERROR,GET_VISA_ACQUIRER_SUMMARY_STATS,GET_VISA_ACQUIRER_SUMMARY_STATS_ERROR,GET_INTERAFFILIATE_ACQUIRER_SUMMARY_STATS,GET_INTERAFFILIATE_ACQUIRER_SUMMARY_STATS_ERROR,GET_INTERAFFILIATE_ISSUER_SUMMARY_STATS,GET_INTERAFFILIATE_ISSUER_SUMMARY_STATS_ERROR,GET_VISA_SUMMARY,GET_VISA_SUMMARY_ERROR,GET_VISA_POSTING_SUMMARY,GET_VISA_POSTING_SUMMARY_LOADING,GET_VISA_POSTING_SUMMARY_ERROR,GET_INTERAFFILIATE_POSTING_SUMMARY,GET_INTERAFFILIATE_POSTING_SUMMARY_ERROR,GET_ADVISEMENT_DETAIL,GET_ADVISEMENT_DETAIL_ERROR,GET_ALL_VSS,GET_ALL_VSS_ERROR,GET_VSS_110,GET_VSS_110_ERROR,GET_VSS_110_SUMMARY,GET_VSS_110_SUMMARY_ERROR,GET_VSS_115,GET_VSS_115_ERROR,GET_VSS_115_SUMMARY,GET_VSS_115_SUMMARY_ERROR,GET_VSS_116,GET_VSS_116_SUMMARY,GET_VSS_116_SUMMARY_ERROR,GET_VSS_116_ERROR,GET_VSS_120,GET_VSS_120_ERROR,GET_VSS_120_SUMMARY,GET_VSS_120_SUMMARY_ERROR,GET_VSS_300,GET_VSS_300_ERROR,GET_VSS_300_SUMMARY,GET_VSS_300_SUMMARY_ERROR,GET_VSS_900,GET_VSS_900_ERROR,GET_VSS_900_SUMMARY,GET_VSS_900_SUMMARY_ERROR,GET_INTERSWITCH_COMPUTATIONS,GET_INTERSWITCH_COMPUTATIONS_ERROR,GET_DAILY_INTERSWITCH_SUMMARY,GET_DAILY_INTERSWITCH_SUMMARY_ERROR} from '../actions/types';


export default function(state ={},action){
    switch(action.type){

        case GET_FILE_SETS:
            return {...state,fileSets:action.payload}
        case GET_FILE_SETS_ERROR:
            return {...state,fileSetsError:action.payload}
        case GET_FILE_SET_DEFINITIONS:
            return {...state,fileSetDefinitions:action.payload}
        case GET_FILE_SET_DEFINITIONS_ERROR:
            return {...state,fileSetDefintionsError:action.payload}
        case CREATE_FILE_SET:
            state.fileSetsPaginated.push(action.payload);
            return {...state,fileSetCreated:action.payload}
        case GET_FILE_SET_STATUS:
            return {...state,fileSetStanding:action.payload}
        case GET_FILE_SET_STATUS_ERROR:
            return {...state,fileSetStandingError:action.payload}
        case ADD_FILE_DEFINITIONS_TO_FILESET:
            return {...state,fileDefinitionAddedToFileset:action.payload}
        case ADD_FILE_DEFINITIONS_TO_FILESET_ERROR:
            return {...state,fileDefinitionAddedToFilesetError:action.payload}
        case CREATE_FILE_SET_ERROR:
            return {...state,fileSetCreatedError:action.payload}
        case UPDATE_FILE_SET:
            let filtered_data = state.fileSetsPaginated.filter(item => item.id !== action.payload.id);
            filtered_data.push(action.payload);
            state.fileSetsPaginated = filtered_data;
            return {...state,fileSetUpdated:action.payload}
        case UPDATE_FILE_SET_ERROR:
            return {...state,fileSetUpdatedError:action.payload}
        case DELETE_FILE_SET:
            const fileSet = state.fileSets.data.filter(item => item.id !== action.payload.id);
            state.fileSets.data = fileSet;
            return {...state,fileSetDeleted:action.payload}
        case DELETE_FILE_SET_ERROR:
            return {...state,fileSetDeletedError:action.payload.response.data}
        case GET_FILESET_BATCHES_SUMMARY:
            return {...state,fileSetBatchSummary:action.payload}
        case GET_FILESET_BATCHES_SUMMARY_ERROR:
            return {...state,fileSetBatchSummaryError:action.payload}
        case GET_FILE_SETS_PAGINATED:
            return {...state,fileSetsPaginated:action.payload}
        case GET_FILE_SETS_PAGINATED_ERROR:
            return {...state,fileSetsPaginateError:action.payload}
        case GET_FILE_SET_BATCHES_PAGINATED:
            return {...state,fileSetBatchesPaginated:action.payload}
        case GET_FILE_SET_BATCHES_PAGINATED_ERROR:
            return {...state,fileSetBatchesPaginatedError:action.payload}
        case GET_FILE_SET_DEFINITION_BATCHES_PAGINATED:
            return {...state,fileSetDefinitionBatchesPaginated:action.payload}
        case GET_FILE_SET_DEFINITION_BATCHES_PAGINATED_ERROR:
            return {...state,fileSetDefinitionBatchesPaginatedError:action.payload}
        case GET_FILE_SET_DEFINITION_BATCHES_TRANSACTIONS_PAGINATED:
            return {...state,fileSetDefinitionBatchesTranactionsPaginated:action.payload}
        case GET_FILE_SET_DEFINITION_BATCHES_TRANSACTIONS_PAGINATED_ERROR:
            return {...state,fileSetDefinitionBatchesTranactionsPaginatedError:action.payload}
        case GET_FILESET_BATCH_DETAIL:
            return {...state,fileSetBatchDetail:action.payload}
        case GET_FILESET_BATCH_DETAIL_ERROR:
            return {...state,fileSetBatchDetailError:action.payload}
        case GET_T112S:
            return {...state,t112s:action.payload}
        case GET_T112S_ERROR:
            return {...state,t112sError:action.payload}
        case GET_T112_SUMMARY:
            return {...state,t112Summary:action.payload,t112SummaryLoading:false}
        case GET_T112_SUMMARY_ERROR:
            return {...state,t112SummaryError:action.payload,t112SummaryLoading:false}
        case GET_T112_SUMMARY_LOADING:
            return {...state,t112SummaryLoading:true}
        case GET_T112_SUMMARY_STATS:
            return {...state,t112SummaryStats:action.payload}
        case GET_T112_SUMMARY_STATS_ERROR:
            return {...state,t112SummaryStatsError:action.payload}
        case GET_T464_SUMMARY:
            return {...state,t464Summary:action.payload}
        case GET_T464_SUMMARY_ERROR:
            return {...state,t464SumaryError:action.payload}
        case GET_T464_SUMMARY_STATS:
            return {...state,t464SummaryStats:action.payload}
        case GET_t464_SUMMARY_STATS_ERROR:
            return {...state,t464SummaryStatsError:action.payload}
        case GET_INTERAFFILIATE_ISSUER_SUMMARY:
            return {...state,interAffiliateIssuerSummary:action.payload}
        case GET_INTERAFFILIATE_ISSUER_SUMMARY_ERROR:
            return {...state,interAffiliateIssuerSummaryError:action}
        case GET_INTERAFFILIATE_ACQUIRER_SUMMARY:
            return {...state,interAffiliateAcquirerSummary:action.payload}
        case GET_INTERAFFILIATE_ACQUIRER_SUMMARY_ERROR:
            return {...state,interAffiliateAcquirerSummaryError:action.payload}
        case GET_INTERAFFILIATE_ACQUIRER_SUMMARY_STATS:
            return {...state,interAffiliateAcquirerSummaryStats:action.payload}
        case GET_INTERAFFILIATE_ACQUIRER_SUMMARY_STATS_ERROR:
            return {...state,interAffiliateAcquirerSummaryStatsError:action.payload}
        case GET_INTERAFFILIATE_ISSUER_SUMMARY_STATS:
            return {...state,interAffiliateIssuerSummaryStats:action.payload}
        case GET_INTERAFFILIATE_ISSUER_SUMMARY_STATS_ERROR:
            return {...state,interAffiliateIssuerSummaryStatsError:action.payload}
        case GET_INTERAFFILIATE_POSTING_SUMMARY:
            return {...state,interAffiliatePostingSummary:action.payload}
        case GET_INTERAFFILIATE_POSTING_SUMMARY_ERROR:
            return {...state,interAffiliatePostingSummaryError:action.payload}
        case GET_T464S:
            return {...state,t464s:action.payload}
        case GET_T461S:
            return {...state,t461s:action.payload}
        case GET_T461S_ERROR:
            return {...state,t461sError:action.payload}
        case GET_T464_TRANSACTIONS:
            return {...state,t464Transactions:action.payload}
        case GET_T464_TRANSACTIONS_ERROR:
            return {...state,t464TransactionsError:action.payload}
        case GET_T140S_TRANSACTIONS:
            return {...state,t140Transactions:action.payload,t140TransactionsLoading:false}
        case GET_T140S_TRANSACTIONS_ERROR:
            return {...state,t140TransactionsError:action.payload,t140TransactionsLoading:false}
        case GET_T140S_TRANSACTIONS_LOADING:
            return {...state,t140TransactionsLoading:true}
        case GET_T112_TRANSACTIONS:
            return {...state,t112Transactions:action.payload}
        case GET_T112_TRANSACTIONS_ERROR:
            return {...state,t112TransactionsError:action.payload}
        case GET_T461_TRANSACTIONS:
            return {...state,t461Transactions:action.payload}
        case GET_T461_TRANSACTIONS_ERROR:
            return {...state,t461TransactionsError:action.payload}
        case GET_T140S:
            return {...state,t140s:action.payload}
        case GET_T140S_ERROR:
            return {...state,t140sError:action.payload}
        case GET_T464S_ERROR:
            return {...state,t464sError:action.payload}
        case GET_FILE_SET:
            return {...state,fileSet:action.payload.data}
        case GET_ADVISEMENT:
            return {...state,advisements:action.payload}
        case GET_ADVISEMENT_ERROR:
            return {...state,advisementsError:action.payload}
        case GET_ADVISEMENT_DETAIL:
            return {...state,advisementDetail:action.payload}
        case GET_ADVISEMENT_DETAIL_ERROR:
            return {...state,advisementDetailError:action.payload}
        case GET_VISA_ISSUER:
            return {...state,visaIssuer:action.payload}
        case GET_VISA_ISSUER_ERROR:
            return {...state,visaIssuerError:action.payload}
        case GET_VISA_ACQUIRER_TRANSACTIONS:
            return {...state,visaAcquirerTransactions:action.payload}
        case GET_VISA_ACQUIRER_TRANSACTIONS_ERROR:
            return {...state,visaAcquirerTransactionsError:action.payload}
        case GET_VISA_ACQUIRER:
            return {...state,visaAcquirer:action.payload}
        case GET_VISA_ACQUIRER_ERROR:
            return {...state,visaAcquirerError:action.payload}
        case GET_VISA_ISSUER_TRANSACTIONS:
            return {...state,visaIssuerTransactions:action.payload}
        case GET_VISA_ISSUER_TRANSACTIONS_ERROR:
            return {...state,visaIssuerTransactionsError:action.payload}
        case GET_INTERAFILIATE_ISSUERS:
            return {...state,interAffiliateiIssuers:action.payload}
        case GET_INTERAFILIATE_ISSUERS_ERROR:
            return {...state,interAffiliateIssuersError:action.payload}
        case GET_INTERAFILIATE_ACQUIRER:
            return {...state,interAffiliateAcquirer:action.payload}
        case GET_INTERAFILIATE_ACQUIRER_ERROR:
            return {...state,interAffiliateAcquirerError:action.payload}
        case GET_ISSUER_TRANSACTIONS:
            return {...state,interAffiliateIssuerTransactions:action.payload}
        case GET_ISSUER_TRANSACTIONS_ERROR:
            return {...state,interAffiliateIssuerTransactionsError:action.payload}
        case GET_ACQUIRER_TRANSACTIONS:
            return {...state,interAffiliateAcquirerTransactions:action.payload}
        case GET_ACQUIRER_TRANSACTIONS_ERROR:
            return {...state,interAffiliateAcquirerTransactionsError:action.payload}
        case GET_INTERAFFILIATE_SUMMARY:
            return {...state,interAffiliateSummary:action.payload}
        case GET_INTERAFFILIATE_SUMMARY_ERROR:
            return {...state,interAffiliateSummaryError:action.payload}
        case GET_VISA_SUMMARY:
            return {...state,visaSummary:action.payload}
        case GET_VISA_SUMMARY_ERROR:
            return {...state,visaSummaryError:action.payload}
        
        case GET_INTERSWITCH_COMPUTATIONS:
            debugger;
            return {...state,interSwitchComputations:action.payload}
        case GET_INTERSWITCH_COMPUTATIONS_ERROR:
            debugger;
            return {...state,interSwitchComputationsError:action.payload}
        case GET_DAILY_INTERSWITCH_SUMMARY:
            debugger;
            return {...state,interSwitchDailyComputationSummary:action.payload}
        case GET_DAILY_INTERSWITCH_SUMMARY_ERROR:
            debugger;
            return {...state,interSwitchDailyComputationSummaryError:action.payload}
        case GET_VISA_POSTING_SUMMARY:
            return {...state,visaPostingSummary:action.payload,visaPostingSummaryLoading:false}
        case GET_VISA_POSTING_SUMMARY_ERROR:
            return {...state,visaPostingSummaryError:action.payload,visaPostingSummaryLoading:false}
        case GET_VISA_POSTING_SUMMARY_LOADING:
            return {...state,visaPostingSummaryLoading:true}
        case GET_VISA_ACQUIRER_SUMMARY:
            return {...state,visaAcquirerSummary:action.payload}
        case GET_VISA_ACQUIRER_SUMMARY_ERROR:
            return {...state,visaAcquirerSummaryError:action.payload}
        case GET_VISA_ISSUER_SUMMARY:
            return {...state,visaIssuerSummary:action.payload}
        case GET_VISA_ISSUER_SUMMARY_ERROR:
            return {...state,visaIssuerSummaryError:action.payload}
        case GET_VISA_ISSUER_SUMMARY_STATS:
            return {...state,visaIssuerSummaryStats:action.payload}
        case GET_VISA_ISSUER_SUMMARY_STATS_ERROR:
            return {...state,visaIssuerSummaryStatsError:action.payload}
        case GET_VISA_ACQUIRER_SUMMARY_STATS:
            return {...state,visaAcquirerSummaryStat:action.payload}
        case GET_VISA_ACQUIRER_SUMMARY_STATS_ERROR:
            return {...state,visaAcquirerSummaryStatError:action.payload}
        case GET_INTERAFFILIATE_SUMMARY_TRANSACTIONS:
            return {...state,interAffiliateSummaryTransactions:action.payload}
        case GET_INTERAFFILIATE_SUMMARY_TRANSACTIONS_ERROR:
            return {...state,interAffiliateSummaryTransactionsError:action.payload}
        case GET_FILE_SET_ERROR:
            return {...state,fileSetError:action.payload}
        case GET_FILESET_BATCH_DEFINITION_DETAIL:
            return {...state,fileSetBatchDefinitionDetail:action.payload}
        case GET_FILESET_BATCH_DEFINITION_DETAIL_ERROR:
            return {...state,fileSetBatchDefinitionDetailError:action.payload}
        case GET_ALL_VSS:
            return {...state,allVss:action.payload}
        case GET_ALL_VSS_ERROR:
            return {...state,allVssError:action.payload}
        case GET_VSS_110:
            return {...state,allVss110:action.payload}
        case GET_VSS_110_ERROR:
            return {...state,allVss110Error:action.payload}
        case GET_VSS_115:
            return {...state,allVss115:action.payload}
        case GET_VSS_115_ERROR:
            return {...state,allVss115Error:action.payload}
        case GET_VSS_116:
            return {...state,allVss116:action.payload}
        case GET_VSS_116_ERROR:
            return {...state,allVss116Error:action.payload}
        case GET_VSS_120:
            return {...state,allVss120:action.payload}
        case GET_VSS_120_ERROR:
            return {...state,allVss120Error:action.payload}
        case GET_VSS_300:
            return {...state,allVss300:action.payload}
        case GET_VSS_300_ERROR:
            return {...state,allVss300Error:action.payload}
        case GET_VSS_900:
            return {...state,allVss900:action.payload}
        case GET_VSS_900_ERROR:
            return {...state,allVss900Error:action.payload}
        case GET_VSS_110_SUMMARY:
            return {...state,vss110Summary:action.payload}
        case GET_VSS_110_SUMMARY_ERROR:
            return {...state,vss110SummaryError:action.payload}
        case GET_VSS_115_SUMMARY:
            return {...state,vss115Summary:action.payload}
        case GET_VSS_115_SUMMARY_ERROR:
            return {...state,vss115SummaryError:action.payload}
        case GET_VSS_116_SUMMARY:
            return {...state,vss116Summary:action.payload}
        case GET_VSS_116_SUMMARY_ERROR:
            return {...state,vss116SummaryError:action.payload}
        case GET_VSS_120_SUMMARY:
            return {...state,vss120Summary:action.payload}
        case GET_VSS_120_SUMMARY_ERROR:
            return {...state,vss120SummaryError:action.payload}
        case GET_VSS_300_SUMMARY:
            return {...state,vss300Summary:action.payload}
        case GET_VSS_300_SUMMARY_ERROR:
            return {...state,vss300SummaryError:action.payload}
        case GET_VSS_900_SUMMARY:
            return {...state,vss900Summary:action.payload}
        case GET_VSS_900_SUMMARY_ERROR:
            return {...state,vss900SummaryError:action.payload}
        case DELETE_FILE_SET_FILE_DEFINITION:
            const remainingFileSetDefinitions = state.fileSetDefinitions.filter(item => item.id !== action.payload);
            state.fileSetDefinitions = remainingFileSetDefinitions;
            return {...state,fileSetFileDefinitionDeleted:'Deleted Successfully!'}
        case DELETE_FILE_SET_FILE_DEFINITION_ERROR:
            return {...state,fileSetDefinitionDeletedError:action.payload}   
        
        
        default:
            return state;
    }
}